from tortoise import fields, models

class PortfolioSummary(models.Model):
    iqama_id = fields.BigIntField(pk=True)  # ✅ Make this the primary key
    cif_id = fields.BigIntField()
    account_number_1 = fields.BigIntField()
    account_balance_1 = fields.BigIntField()
    account_type_1 = fields.CharField(max_length=255)
    status_1 = fields.CharField(max_length=255)
    recent_transaction_type_1 = fields.CharField(max_length=255)
    recent_transaction_date_1 = fields.CharField(max_length=255)
    recent_transactions_amount_1 = fields.BigIntField()
    recent_transaction_type_2 = fields.CharField(max_length=255)
    recent_transactions_date_2 = fields.CharField(max_length=255)
    recent_transactions_amount_2 = fields.BigIntField()
    recent_transactions_transaction_type_3 = fields.CharField(max_length=255)
    recent_transactions_date_3 = fields.CharField(max_length=255)
    recent_transactions_amount_3 = fields.BigIntField()
    bill_transaction_type_1 = fields.CharField(max_length=255)
    bill_due_date_1 = fields.CharField(max_length=255)
    bill_service_type_1 = fields.CharField(max_length=255)
    bill_amount_1 = fields.BigIntField()
    bill_transaction_type_2 = fields.CharField(max_length=255)
    bill_due_date_2 = fields.CharField(max_length=255)
    bill_service_type_2 = fields.CharField(max_length=255)
    bill_amount_2 = fields.BigIntField()
    recent_transfers_date_1 = fields.DateField(null=True)
    recent_transfers_beneficiary_name_1 = fields.CharField(max_length=255)
    recent_transfers_bank_name_1 = fields.CharField(max_length=255)
    recent_transfers_amount_1 = fields.BigIntField()
    recent_transfers_date_2 = fields.DateField(null=True)
    recent_transfers_beneficiary_name_2 = fields.CharField(max_length=255)
    recent_transfers_bank_name_2 = fields.CharField(max_length=255)
    recent_transfers_amount_2 = fields.BigIntField()
    account_number_2 = fields.BigIntField()
    account_balance_2 = fields.BigIntField()
    account_type_2 = fields.CharField(max_length=255)
    status_2 = fields.CharField(max_length=255)

    class Meta:
        table = "portfolio_summary"
